# Generated by Django 3.1.7 on 2021-03-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='null', max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('org', models.CharField(max_length=200)),
                ('type_org', models.CharField(default='School', max_length=100)),
                ('designation', models.CharField(max_length=150)),
                ('phone', models.PositiveIntegerField()),
                ('purpose', models.TextField()),
                ('detail', models.TextField()),
                ('theme', models.CharField(max_length=250)),
                ('guidelines', models.TextField()),
                ('elig_cri', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='null', max_length=50)),
                ('School_Name', models.CharField(max_length=50)),
                ('School_Phone_no', models.CharField(max_length=150)),
                ('School_Email_address', models.EmailField(max_length=100)),
                ('School_Address', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=100)),
                ('Student_Name', models.CharField(max_length=50)),
                ('Contact_no', models.CharField(max_length=150)),
                ('Email_address', models.EmailField(max_length=100)),
                ('House_Address', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=100)),
                ('Title_of_your_project', models.CharField(max_length=200)),
                ('Question_or_Problem', models.CharField(max_length=100)),
                ('Hypothesis_or_possible_solution', models.CharField(max_length=50)),
                ('Materials_needed', models.CharField(max_length=150)),
                ('Results', models.CharField(max_length=100)),
                ('Image_of_Project', models.ImageField(default='', upload_to='core/images')),
                ('Link_of_your_project', models.URLField()),
                ('host_id', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
